version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: my_backend
    restart: always
    env_file:
      - ../.env
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ../../HelpingHouse
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: my_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
