export const HELPING_HOUSE_LOGIN ={
    HELPING_HOUSE_LOGIN_REQUEST : "HELPING_HOUSE_LOGIN_REQUEST",
    HELPING_HOUSE_LOGIN_SUCCESS : "HELPING_HOUSE_LOGIN_SUCCESS",
    HELPING_HOUSE_LOGIN_FAILURE : "HELPING_HOUSE_LOGIN_FAILURE",
}

export const DONER_LOGIN ={
    DONER_LOGIN_REQUEST : "DONER_LOGIN_REQUEST",
    DONER_LOGIN_SUCCESS : "DONER_LOGIN_SUCCESS",
    DONER_LOGIN_FAILURE : "DONER_LOGIN_FAILURE",
}

export const SIGNUP_DONER ={
    SIGNUP_DONER_REQUEST : "SIGNUP_DONER_REQUEST",
    SIGNUP_DONER_SUCCESS : "SIGNUP_DONER_SUCCESS",
    SIGNUP_DONER_FAILURE: "SIGNUP_DONER_FAILURE"
 }