export const GET_ALL_HELPING_HOUSES = {
  GET_ALL_HELPING_HOUSES_REQUEST: "GET_ALL_HELPING_HOUSES_REQUEST",
  GET_ALL_HELPING_HOUSES_SUCCESS: "GET_ALL_HELPING_HOUSES_SUCCESS",
  GET_ALL_HELPING_HOUSES_FAILURE: "GET_ALL_HELPING_HOUSES_FAILURE",
};

export const GET_HELPING_HOUSE_BY_ID = {
  GET_HELPING_HOUSE_BY_ID_REQUEST: "GET_HELPING_HOUSE_BY_ID_REQUEST",
  GET_HELPING_HOUSE_BY_ID_SUCCESS: "GET_HELPING_HOUSE_BY_ID_SUCCESS",
  GET_HELPING_HOUSE_BY_ID_FAILURE: "GET_HELPING_HOUSE_BY_ID_FAILURE",
};

export const GET_HELPING_HOUSE_DASHBOARD = {
  GET_HELPING_HOUSE_DASHBOARD_REQUEST: "GET_HELPING_HOUSE_DASHBOARD_REQUEST",
  GET_HELPING_HOUSE_DASHBOARD_SUCCESS: "GET_HELPING_HOUSE_DASHBOARD_SUCCESS",
  GET_HELPING_HOUSE_DASHBOARD_FAILURE: "GET_HELPING_HOUSE_DASHBOARD_FAILURE",
};

export const CREATE_PERSON = {
  CREATE_PERSON_REQUEST: "CREATE_PERSON_REQUEST",
  CREATE_PERSON_SUCCESS: "CREATE_PERSON_SUCCESS",
  CREATE_PERSON_FAILURE: "CREATE_PERSON_FAILURE",
};

export const DELETE_PERSON = {
  DELETE_PERSON_REQUEST: "DELETE_PERSON_REQUEST",
  DELETE_PERSON_SUCCESS: "DELETE_PERSON_SUCCESS",
  DELETE_PERSON_FAILURE: "DELETE_PERSON_FAILURE",
};

export const EDIT_HELPING_HOUSE = {
  EDIT_HELPING_HOUSE_REQUEST: "EDIT_HELPING_HOUSE_REQUEST",
  EDIT_HELPING_HOUSE_SUCCESS: "EDIT_HELPING_HOUSE_SUCCESS",
  EDIT_HELPING_HOUSE_FAILURE: "EDIT_HELPING_HOUSE_FAILURE",
};
